[build]
  # 1. Clona Flutter (versiÃ³n estable)
  # 2. Habilita la web
  # 3. Construye la app
  command = "([ -d flutter ] || git clone https://github.com/flutter/flutter.git -b stable) && ./flutter/bin/flutter config --enable-web && ./flutter/bin/flutter build web --release"
  
  # Carpeta donde Flutter deja los archivos listos para publicar
  publish = "build/web"

