name: finanzapp
description: "Web App de Finanzas Personales."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  provider: ^6.0.0
  file_picker: ^8.0.0
  
  # State Management
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5

  # Firebase
  firebase_core: ^2.24.2
  firebase_auth: ^4.16.0
  cloud_firestore: ^4.14.0

  # UI / UX
  fl_chart: ^1.1.1
  google_fonts: ^6.1.0
  intl: ^0.20.0
  font_awesome_flutter: ^10.7.0 # Iconos adicionales útiles para Web
  flutter_animate: ^4.5.0 # Required for animations

  # Data / Utils
  uuid: ^4.3.3
  equatable: ^2.0.5
  json_annotation: ^4.8.1
  csv: ^6.0.0 # Para importación bancaria
  shared_preferences: ^2.5.4


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.8
  riverpod_generator: ^2.4.0
  json_serializable: ^6.7.1
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  
  # Assets para el futuro (Logo, iconos custom)
  assets:
    - assets/images/
